// Example of Localization in React Native Multi Language App
// https://aboutreact.com/localization-in-react-native/
 
import LocalizedStrings from 'react-native-localization';
 
const StringsOfLanguages = new LocalizedStrings({
  en: {
    isLoading: 'Loading Files...',
    loginFB: 'Login Session Facebook',
    loginGL: 'Login Session Google',
    welcome: 'Welcome ?',
    language: 'Select Your Language ?',
    second: 'I am fine ',
    footer: 'Mi Huerto Project, All rights reserved to the Guia Agricola group.',
    web: 'https://www.usc.edu.co/',
    login: 'LOGIN SESSION',
    bannerlogin: 'Is Important Login Session!',
    plants: 'Plants',
    profile: 'Profile',
    title1: 'My Plants',
    title2: 'My Plants',
    title3: 'Categories',
    title4: 'Profile',
    categoriestitle1: 'Frutals',
    categoriestitle2: 'Vegetals',
    categoriestitle3: 'Aromatics',
    categoriestitle4: 'Flowers',
    information: 'Information Of cultivate',
    cultive: "How to cultivate",
    maceta: "Pot Size",
    transplant: "Transplanting Plants",
    Clime: "Thermal Floor",
    temperatureMax: "Ideal Maxium Temperature",
    temperatureMin: "Ideal Minimum Temperature",
    amountIrrigation: "Amount of irrigation",
    solar: "Solar Light",
    heighMax: "Maximum height",
    depth: "Seed Planting Depth",
    separationPlants: "Separation Between Plants",
    type: "Soil Type",
    ph: "Soil Ph",
    moon: "Recommended Moon for Planting",
    next: 'Skip Session',
  },
  es: {
    isLoading: 'Cargando',
    welcome: 'Bienvenido!',
    loginFB: 'Inicia Sesion Con Facebook',
    loginGL: 'Inicia Sesion Con Google',
    language: 'Selecciona Tu Idioma!',
    second: 'Sientase Comodo!',
    footer: 'Proyecto Mi Huerto!, Todos Los Derechos reservados a el grupo Guia Agricola',
    web: 'https://www.usc.edu.co/',
    login: 'INICIAR SESION',
    bannerlogin: 'Es Importante Iniciar Sesion!',
    plants: 'Plantas',
    profile: 'Perfil',
    title1: 'Mis Plantas',
    title2: 'Abonos Organicos',
    title3: 'Categorias',
    title4: 'Perfil',
    categoriestitle1: 'Frutales',
    categoriestitle2: 'Vegetales',
    categoriestitle3: 'Aromaticas',
    categoriestitle4: 'Flores',
    information: 'Informacion De Cultivo',
    //Information
    name: "Nombre del Cultivo",
    namescientific: "Nombre Cientifico",
    typeCultive: "Tipo de Cultivo",    
    buttonSend: "Sembrar Ahora",
    // Cuando Cultivar
    cultive: "Cuando Cultivar",
    germiny: "Germina En",
    harvest: "Se Puede Cosechar En",
    season: "Siembra En La Temporada",
    //Como Cultivar
    howCultive: "Como Cultivar",
    maceta: "Tamaño Maceta",
    transplant: "Transplantar Plantas",
    homePlant: "¿Se Puede Plantar En Casa?",
    Clime: "Piso Termico",
    temperatureMax: "Temperatura Maxima ideal",
    temperatureMin: "Temperatura Minima ideal",
    amountIrrigation: "Cantidad De Riegos",
    solar: "Luz Solar",
    heighMax: "Altura Maxima",
    depth: "Profundidad Al Sembrar La Semilla",
    separationPlants: "Separacion Entre Plantas",
    type: "Tipo De Suelo",
    ph: "Ph Del Suelo",
    moon: "Luna Recomendada Para Sembrar",
    next: 'Omitir Inicio De Sesion',
  },
});
 
export default StringsOfLanguages;